
CREATE TABLE item (
-- HERE id column is generated automatically when we create item object without set a value to id , so in this case generated it by default automatically
	id            NUMBER   GENERATED BY DEFAULT ON NULL AS IDENTITY  CONSTRAINT item_id_prim PRIMARY KEY,
	name          VARCHAR2(100)    CONSTRAINT item_name_unique  UNIQUE,
	price         NUMBER,
	total_number  NUMBER,
);


DROP TABLE item;


SELECT * FROM item;

INSERT INTO item (name,price,total_number) VALUES ('item2',50,5);